// assets/js/react.toggle-content/ToggleContent.jsx
import React, { useState } from 'react';

export default function ToggleContent(props) {
    const [shown, setShown] = useState(props.initiallyShown | false);

    const toggle = () => {
        setShown(!shown);
    };

    const buttonClass = "toggle-button " + (
        shown ? "on" : "off"
    );

    return (
        <div>
            <button className={buttonClass} onClick={toggle}>Toggle</button>
            { shown ? <Content/> : null}
        </div>
    );
}

function Content() {
    return (
        <div className="toggle-content">
            <p>Hello</p>
            <p>World</p>
        </div>
    );
}

// assets/js/vue.toggle-content/ToggleContent.vue
<template>
  <div>
    <button class="toggle-button" v-on:click="toggle" v-bind:class="{'on': shown, 'off': !shown}">Toggle</button>
    <div class="toggle-content" v-if="shown"><!-- style="display: none;" v-bind:style="{'display': null}" -->
      <p>Hello</p>
      <p>World</p>
    </div>
  </div>
</template>

<script>
export default {
  props: [
    'initiallyShown'
  ],
  data() {
    return {
      shown: this.initiallyShown
    }
  },
  methods: {
    toggle() {
      this.shown = !this.shown;
    }
  }
}
</script>
